spring:
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${MYSQL_HOST:172.16.7.200}:${MYSQL_PORT:3306}/Oauth?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: root
      initial-size: 10
      max-active: 400
      min-idle: 2
      max-wait: 60000
      removeAbandoned: true
      removeAbandonedTimeout: 600
      logAbandoned: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: false
        slf4j:
          enabled: true
          statement-log-error-enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        reset-enable: false
        login-password: root
        login-username: root

  redis:
    host: 172.16.6.200
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


yuelao:
  authentication:
    loginPage: http://www.baidu.com
    tokenSettings:
      expires: 30
      refreshExpires: 60

